# Deletes assets found unreachable from MainMenu.unity / GameBoard.unity / Resources.
# CLOSE UNITY FIRST. Review before running. Sends to Recycle Bin, not permanent delete.
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName Microsoft.VisualBasic
$root = "
c:\Users\Dave's Comp\source\repos\Archon's Rise
"
function Recycle([string]$p) {
  if (Test-Path -LiteralPath $p) {
    [Microsoft.VisualBasic.FileIO.FileSystem]::DeleteFile($p, "OnlyErrorDialogs", "SendToRecycleBin")
  }
}
$targets = @(
  'Assets\Images\Tiny Fantasy Icons\All_Icons_512.psd'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\1_normal_ui_set free.psd'
  'Assets\Images\Simple Fantasy GUI\PSD\Simple_Fantasy_GUI_ALL.psd'
  'Assets\Images\StoneUI\OrherUI_4-2K\5.png'
  'Assets\Images\StoneUI\OrherUI_4-2K\3.png'
  'Assets\Images\StoneUI\OrherUI_4-2K\2.png'
  'Assets\Images\Blackthornprod\100 Fantasy Characters Pack\Sprites\characters.png'
  'Assets\Images\StoneUI\OrherUI_4-2K\button_rock_Play3.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\4.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\6.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\5.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\3.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\2.png'
  'Assets\Images\StoneUI\Samples\frames5.png'
  'Assets\Images\StoneUI\Samples\frames6.png'
  'Assets\Images\StoneUI\Samples\frames2.png'
  'Assets\Images\StoneUI\Samples\frames3.png'
  'Assets\Images\StoneUI\Samples\frames1.png'
  'Assets\Images\Simple Fantasy GUI\PSD\Loading_Bar.psd'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\1_normal_ui_set-free.png'
  'Assets\Images\StoneUI\OrherUI_4-2K\button_rock_Play.png'
  'Assets\Images\Card_Shirts_Lite\PNG\Card_shirt_01.png'
  'Assets\Images\Simple Fantasy GUI\PSD\Quest_Panel.psd'
  'Assets\Images\Simple Fantasy GUI\PSD\Characer_Panel.psd'
  'Assets\Images\Blackthornprod\100 Fantasy Characters Pack\Sprites\bg9.png'
  'Assets\Images\Simple Fantasy GUI\PSD\Inventory_Box.psd'
  'Assets\Images\StoneUI\OtherUI_2-1K\button_rock_Play3.png'
  'Assets\Images\StoneUI\Samples\button_rock_Play3.png'
  'Assets\Images\StoneUI\Samples\frames.png'
  'Assets\Images\StoneUI\OrherUI_4-2K\button_rock_Play2.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\1.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\button_rock_Play5.png'
  'Assets\Images\StoneUI\Samples\button_rock_Play5.png'
  'Assets\Images\StoneUI\Samples\button_moss_green.png'
  'Assets\Images\StoneUI\Samples\button_moss_red.png'
  'Assets\Images\StoneUI\Samples\button_rock_Play4.png'
  'Assets\Images\StoneUI\Samples\button_moss_purple.png'
  'Assets\Images\StoneUI\Samples\button_moss_blue.png'
  'Assets\TextMesh Pro\Documentation\TextMesh Pro User Guide 2016.pdf'
  'Assets\Images\StoneUI\Samples\button_moss_yellow.png'
  'Assets\Images\Simple Fantasy GUI\PSD\Menu_Bar.psd'
  'Assets\Images\StoneUI\OtherUI_4k+\button76.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button62.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button69.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button83.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button73.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button75.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button59.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button78.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button66.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button61.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button77.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button82.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button68.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button80.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button63.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button85.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button71.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button70.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button72.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button84.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button58.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button74.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button65.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button81.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button64.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button60.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button79.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button67.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar22.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar20.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar21.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar23.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\button_rock_Play.png'
  'Assets\Images\StoneUI\Samples\button_rock_Play.png'
  'Assets\Images\StoneUI\Samples\button_rock_yellow.png'
  'Assets\Images\Simple Fantasy GUI\PSD\Login_Bar.psd'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_trader.png'
  'Assets\Images\Simple Fantasy GUI\PSD\Character_Bar.psd'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_hand.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_gold.png'
  'Assets\Images\StoneUI\Samples\button_rock_blue.png'
  'Assets\Images\StoneUI\Samples\button_rock_grey.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button55.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button54.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button52.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button57.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button51.png'
  'Assets\Images\StoneUI\Samples\button_rock_red.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button56.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button53.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar19.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar19a.png'
  'Assets\Images\StoneUI\Samples\button_rock_violet.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_broken_sword.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar19b.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Loading Bar\LoadingDemo.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_healing_potion.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_027.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_232.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_drop.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_trap.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_351.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_348.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_151.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_229.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_crossbow.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_474.png'
  'Assets\Images\StoneUI\Samples\button_rock_black.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_might.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_468.png'
  'Assets\Images\StoneUI\OtherUI_2-1K\button_rock_Play2.png'
  'Assets\Images\StoneUI\Samples\button_rock_Play2.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_320.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_518.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_423.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_299.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_193.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_rain_of_arrows.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_492.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_384.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_159.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_237.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_226.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_114.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_075.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_235.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_469.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_078.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_395.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_096.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_369.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_hammer.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_244.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_507.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_418.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_416.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_022.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_123.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_010.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_482.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_473.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_099.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_406.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_431.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_048.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_137.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_376.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_458.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_273.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_464.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_021.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_503.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_axe.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_230.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_020.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_456.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_421.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_124.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_fireball.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_428.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_512.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_317.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_420.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_303.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_luck_horseshoe.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_047.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_013.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_502.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_153.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_073.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_386.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_112.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_304.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_362.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_516.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_332.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_247.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_132.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_147.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_243.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_160.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_210.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_168.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_225.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_308.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_088.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_214.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_146.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_321.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_260.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_297.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_519.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_224.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_142.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_497.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_363.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_113.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_322.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_276.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_017.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_511.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_271.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_149.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_189.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_277.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_407.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_411.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_255.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_439.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_275.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_521.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_353.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_345.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_118.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_068.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_051.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_demon.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_152.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_145.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_366.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_097.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_077.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_015.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_256.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_493.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_459.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_122.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_410.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_245.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_446.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_064.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_135.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_472.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_199.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_031.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_155.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_162.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_378.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_181.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_412.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_101.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_328.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_213.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_425.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_131.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_079.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_495.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_253.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_319.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_339.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_388.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_dual_sword.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_016.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_265.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_266.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_514.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_501.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_158.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_325.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_430.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_038.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_368.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_119.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_504.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_025.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_487.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_261.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_trap_spears.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_185.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_274.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_221.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_450.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_107.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_218.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_198.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_498.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_305.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_476.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_220.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_279.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_372.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_128.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_520.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_379.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_233.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_479.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_fire_hand.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_463.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_052.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_231.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_056.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_254.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_445.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_183.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_116.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_194.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_089.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_066.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_462.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_284.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_186.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_449.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_405.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_478.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_307.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_367.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_195.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_138.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_419.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_054.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_251.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_157.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_335.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_350.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_028.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_002.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_282.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_222.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_205.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_026.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_239.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_399.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_061.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_457.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_055.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_241.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_381.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_126.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_249.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_359.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_517.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_499.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_280.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_134.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_058.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_223.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_032.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_007.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_364.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_330.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_465.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_506.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_491.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_246.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_375.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_287.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_270.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_156.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_409.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_165.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_360.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_268.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_105.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_337.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_209.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_050.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_326.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_150.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_163.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_435.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_167.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_154.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_486.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_029.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_309.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_291.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_311.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_315.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_111.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_236.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_219.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_104.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_401.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_432.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_278.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_377.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_081.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_tripple_arrows_2.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_477.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_046.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_316.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_515.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_496.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_352.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_488.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_074.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_471.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_085.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_216.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_076.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_035.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_475.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_267.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_trap_spikes.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_415.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_383.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_289.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_bow.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_451.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_358.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_053.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_042.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_361.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_490.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_505.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_182.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_071.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_461.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_443.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_130.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_283.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_192.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_394.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_258.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_484.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_234.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_004.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_095.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_057.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_140.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_161.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_018.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_036.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_164.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_500.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_117.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_424.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_166.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_257.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_341.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_327.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_072.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_444.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_344.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_215.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_259.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_144.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_454.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_510.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_197.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_314.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_196.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_121.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_408.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_397.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_442.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_129.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_188.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_041.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_shield.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_373.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_115.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_485.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_509.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_069.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_033.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_039.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_045.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_434.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_100.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_263.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_191.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_102.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_177.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_212.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_060.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_242.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_094.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_480.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_001.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_062.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_427.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_044.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_333.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_187.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_382.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_008.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_200.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_043.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_264.png'
  'Assets\Images\500FreeSkillIcons\Icons\traitElusive.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_429.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_470.png'
  'Assets\Images\Turbo Disk\Dark Fantasy RPG Icons - Free Basic Pack (25)\Icons\512\icon_sword.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_483.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_003.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_250.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_059.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_508.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_385.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_170.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_403.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_312.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_489.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_414.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_049.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_380.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_300.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_494.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_346.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_207.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_433.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_467.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_109.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_030.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_240.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_141.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_452.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_293.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_302.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_422.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_324.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_006.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_211.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_037.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_086.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_262.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_202.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_453.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_110.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_203.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_398.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_005.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_014.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_447.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_331.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_389.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_238.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_313.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_323.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_204.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_023.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_301.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_437.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_190.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_269.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_354.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_127.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_106.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_063.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_139.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_227.png'
  'Assets\Images\500FreeSkillIcons\Icons\town.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_400.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_136.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_148.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_342.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_082.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_404.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_286.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_347.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_336.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_306.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_108.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_455.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_091.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_466.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_248.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_184.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_208.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_318.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_292.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_034.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_288.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_125.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_481.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_371.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_448.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_201.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_298.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_080.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_084.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_171.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_387.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_174.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_441.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_438.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_009.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_143.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_090.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_173.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_294.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_172.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_012.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_334.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_252.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_180.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_011.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_103.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_426.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_290.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_392.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_523.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_374.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar18.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_175.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_092.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_228.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_460.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_065.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_393.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_176.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_356.png'
  'Assets\Images\StoneUI\Samples\slider.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_343.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_357.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_083.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_402.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_217.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_513.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_355.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-HDRP LIT.shadergraph'
  'Assets\Images\500FreeSkillIcons\Icons\skill_040.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar18a.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_391.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-URP Lit.shadergraph'
  'Assets\Images\500FreeSkillIcons\Icons\skill_390.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_285.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-HDRP UNLIT.shadergraph'
  'Assets\Images\500FreeSkillIcons\Icons\skill_169.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_120.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_310.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_370.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-URP Unlit.shadergraph'
  'Assets\Images\500FreeSkillIcons\Icons\skill_024.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_396.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_413.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_272.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_179.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_329.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_178.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar18b.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_087.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_338.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_349.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_281.png'
  'Assets\Images\StoneUI\Samples\button_white.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button16.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button20.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button9.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button13.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_295.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button19.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button12.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button31.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button21.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button35.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar10.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button14.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button23.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar4.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar9.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button28.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button34.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar3.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button18.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar8.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button36.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar2.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar13.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar12.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button27.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar15.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button11.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar16.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar14.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar11.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button15.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button29.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button8.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button2.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button6.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button33.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button17.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_436.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button10.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar1.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button5.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button26.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button30.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button7.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button22.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button32.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar5.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button25.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button4.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar6.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button1.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button3.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button42.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button38.png'
  'Assets\Images\500FreeSkillIcons\Icons\skill_296.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar7.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button41.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button43.png'
  'Assets\Plugins\Demigiant\DOTween\DOTween.XML'
  'Assets\Animations\CardFlip.anim'
  'Assets\Images\Images\crossed_swords.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button40.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button37.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button39.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\10. Example of Color Alterations\Color Alterations.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\forestPineSnowCovered00.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\9. Button States\Button States.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\UI board Small  stone.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\jungle00.png'
  'Assets\Images\Tiny Swords\Units\Enemy Pack - Promo\Enemy Pack_Promo.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\UI board Large Set.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\volcanoActive00.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\forestBroadleaf00.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\plains_castle00.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\mountain00.png'
  'Assets\Terrain Tile Hex Samples\Hex Samples\hexForestPineSnowCovered00.png'
  'Assets\Terrain Tile Hex Samples\Hex Samples\hexJungle00.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\plains00.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\desertYellowCactiForest00.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Quest Panel\QuestDemo.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_Purple.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_Green.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_Orange.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_Blue.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_White.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_Purple 1.xcf'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_Red.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_Yellow.png'
  'Assets\Images\Tiny Fantasy Icons\Time\Clock_A.png'
  'Assets\Images\Tiny Fantasy Icons\Books\Book_C_Open.png'
  'Assets\Images\Tiny Fantasy Icons\Books\Book_D_Open.png'
  'Assets\Images\Tiny Fantasy Icons\Chests\ChestA.png'
  'Assets\Images\Tiny Fantasy Icons\Pendants\Pendant_F.png'
  'Assets\Images\Tiny Fantasy Icons\Books\Book_A_Open.png'
  'Assets\Images\Tiny Fantasy Icons\Books\Book_B_Open.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Epic-_Diamond.png'
  'Assets\Images\Tiny Fantasy Icons\Pendants\Pendant_D.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Epic-_Emerald.png'
  'Assets\Images\Tiny Fantasy Icons\Books\Book_A_Close.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\CharacterDemo.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Huge_Diamond.png'
  'Assets\Images\Tiny Fantasy Icons\Books\Book_C_Close.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Epic-_Ruby.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button86.png'
  'Assets\Images\Tiny Fantasy Icons\Presents\Present_A.png'
  'Assets\Images\Tiny Fantasy Icons\Time\Compas_A.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Huge_Emerald.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Close_Purple.png'
  'Assets\Images\Tiny Fantasy Icons\Chests\ChestB.png'
  'Assets\Images\Tiny Fantasy Icons\Pouches\Pouche_C.png'
  'Assets\Images\Tiny Fantasy Icons\Pendants\Pendant_B.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar24.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Huge_Ruby.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Close_Green.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Close_Yellow.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button90.png'
  'Assets\Images\Tiny Fantasy Icons\Books\Book_B_Close.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Close_Blue.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Close_White.png'
  'Assets\Images\Tiny Fantasy Icons\Runes\Rune_D.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Close_Orange.png'
  'Assets\Images\Tiny Fantasy Icons\Presents\Present_B.png'
  'Assets\Images\Tiny Fantasy Icons\Pendants\Pendant_C.png'
  'Assets\Images\Tiny Fantasy Icons\Books\Book_D_Close.png'
  'Assets\Images\Tiny Fantasy Icons\Chests\ChestC.png'
  'Assets\Images\Tiny Fantasy Icons\Pouches\Pouche_A.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Small_Diamond.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Large_Diamond.png'
  'Assets\Images\Tiny Fantasy Icons\PowerUps\Heart_A.png'
  'Assets\Images\Tiny Fantasy Icons\Pendants\Pendant_E.png'
  'Assets\Images\Tiny Fantasy Icons\Keys\Key_B.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Close_Red.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button89.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Large_Emerald.png'
  'Assets\Images\Tiny Fantasy Icons\Pouches\Pouche_B.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\UI board Medium Set.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Small_Emerald.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button87.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button92.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Large_Ruby.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Blackhole.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button93.png'
  'Assets\Images\Tiny Fantasy Icons\Presents\Present_C.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Pound.png'
  'Assets\Images\Tiny Fantasy Icons\Runes\Rune_F.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Arrow_Barrage.png'
  'Assets\Images\Tiny Fantasy Icons\PowerUps\Bolt_A.png'
  'Assets\Images\Tiny Fantasy Icons\Runes\Rune_A.png'
  'Assets\Images\Images\text-box-frame-transparent-background.png'
  'Assets\Images\Tiny Fantasy Icons\Runes\Rune_C.png'
  'Assets\Images\Tiny Fantasy Icons\Runes\Rune_E.png'
  'Assets\Images\Tiny Fantasy Icons\Runes\Rune_B.png'
  'Assets\Images\Tiny Fantasy Icons\Keys\Key_C.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Medium_Diamond.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button88.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_SpiritArrows.png'
  'Assets\Images\Tiny Fantasy Icons\Scrolls\Scroll_Open_Purple 1.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Medium_Emerald.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Tiny_Diamond.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Small_Ruby.png'
  'Assets\Images\Tiny Fantasy Icons\Keys\Key_D.png'
  'Assets\Images\Tiny Fantasy Icons\PowerUps\Star_A.png'
  'Assets\Images\Tiny Fantasy Icons\Keys\Key_A.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Medium_Ruby.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Beam.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Tiny_Emerald.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_MeteorShower.png'
  'Assets\Images\Tiny Fantasy Icons\Pendants\Pendant_A.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Slide.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_PsycicAttack.png'
  'Assets\Images\Tiny Fantasy Icons\PowerUps\Bolt_B.png'
  'Assets\Images\Tiny Fantasy Icons\PowerUps\Heart_B.png'
  'Assets\Images\Tiny Fantasy Icons\Gems\Gems_Tiny_Ruby.png'
  'Assets\Images\RPG_inventory_icons\f.PNG'
  'Assets\Scripts\Input\TestResults_20260707_200903.xml'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Recon.png'
  'Assets\Terrain Tile Hex Samples\Tile Samples\oceanCalm00.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Slash.png'
  'Assets\Images\RPG_inventory_icons\armor.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Chop.png'
  'Assets\Images\IconArt\UI Assets\Ability_Skill_Icons\UI_Skill_Icon_Claw.png'
  'Assets\Images\RPG_inventory_icons\pants.png'
  'Assets\Images\Images\_24_text-frame-png_frames-transparent-images-pluspng-decorative-text-box-png-600x369-png-download-pngkit.png'
  'Assets\Images\RPG_inventory_icons\Meat.png'
  'Assets\Images\RPG_inventory_icons\belts.png'
  'Assets\Images\RPG_inventory_icons\hp.png'
  'Assets\Images\RPG_inventory_icons\coins.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button45.png'
  'Assets\Plugins\Demigiant\DOTween\DOTween.dll.mdb'
  'Assets\Plugins\Demigiant\DOTween\Editor\DOTweenEditor.dll'
  'Assets\Images\RPG_inventory_icons\boots.png'
  'Assets\Terrain Tile Hex Samples\Hex Samples\hexUnderDirt00.png'
  'Assets\Images\StoneUI\Samples\SampleScene.unity'
  'Assets\Images\StoneUI\OtherUI_4k+\button_rock_greystar17.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button49.png'
  'Assets\Images\RPG_inventory_icons\cloaks.PNG'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\UI board Medium  parchment.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Inventory\InventoryDemo.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button48.png'
  'Assets\Images\RPG_inventory_icons\gloves.PNG'
  'Assets\Images\StoneUI\OtherUI_4k+\button50.png'
  'Assets\Images\RPG_inventory_icons\bracers.PNG'
  'Assets\Images\StoneUI\OtherUI_4k+\button47.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Bar\CharacterDemo.png'
  'Assets\Images\IconArt\Demo\SKILL SET DEMO.unity'
  'Assets\Images\RPG_inventory_icons\shoulders.png'
  'Assets\Terrain Tile Hex Samples\Example Scene\TileHexExampleScene.unity'
  'Assets\Images\StoneUI\OtherUI_4k+\button44.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Loading Bar\Decoration.png'
  'Assets\Images\RPG_inventory_icons\axe.png'
  'Assets\Images\StoneUI\OtherUI_4k+\button46.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Menu Panel\MenuDemo.png'
  'Assets\Images\RPG_inventory_icons\necklace.PNG'
  'Assets\Images\RPG_inventory_icons\rings.PNG'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\Atlas.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\IRONY TITLE  Large.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\7. Knives\512\1. Knives.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\8. Knives.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\UI board Small  parchment.png'
  'Assets\Images\RPG_inventory_icons\ingots.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\notice.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Login Panel\LoginDemo.png'
  'Assets\Images\Hero Knight - Pixel Art\Demo\Demo.unity'
  'Assets\Terrain Tile Hex Samples\Tile Samples\below_dirt00.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Quest Panel\Quest_Box.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\IRONY TITLE  empty.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_AnimController.controller'
  'Assets\Terrain Tile Hex Samples\Tile Samples\base00.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\3. Button\512\2. Combined.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\Character_Box.png'
  'Assets\Terrain Tile Hex Samples\Hex Samples\hexUnderOcean00.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Inventory\Inventory_Box.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Bar\Character_Box.png'
  'Assets\Plugins\Demigiant\DOTween\Editor\Imgs\Header.jpg'
  'Assets\Images\Simple Fantasy GUI\PNG\Inventory\Inventory_Slots.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\8. Coin\512\1. Coin.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\512\3. Combined.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\5. Sword.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\512\1. Card.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\Atlas.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\TextBTN_New-Start.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Login Panel\Login_Box.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\8. Knives.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\7. Knives\256\1. Knives.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\4. Button.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Bar\Player_Frame.png'
  'Assets\Images\Tiny Swords\Buildings\Yellow Buildings\Castle.png'
  'Assets\Images\Tiny Swords\Buildings\Blue Buildings\Castle.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\6. Knife\512\1. Knife.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\7. Knife.png'
  'Assets\Images\Tiny Swords\Buildings\Purple Buildings\Castle.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\TextBTN_New-Start_Pressed.png'
  'Assets\Images\Tiny Swords\Buildings\Red Buildings\Castle.png'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\FreeSamplesHex.prefab'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\TextBTN_Cancel.png'
  'Assets\Images\Hero Knight - Pixel Art\Demo\HeroKnight_Green.prefab'
  'Assets\Images\Hero Knight - Pixel Art\Demo\HeroKnight_Yellow.prefab'
  'Assets\Images\Simple Fantasy GUI\PNG\Loading Bar\Background_Bar.png'
  'Assets\Images\Hero Knight - Pixel Art\Demo\HeroKnight.prefab'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\Exclamation_Yellow.png'
  'Assets\Images\GroundTile.prefab'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\Exclamation_Gray.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\TextBTN_Cancel_Pressed.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_Idle.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_Idle.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_Idle.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_Idle.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_Idle.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\3. Button\512\1. Button.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF SSD.shader'
  'Assets\Images\Simple Fantasy GUI\PNG\Quest Panel\Crystal_Icon.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Crystal_Icon.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Archer\Archer_Shoot.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Archer\Archer_Shoot.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Archer\Archer_Shoot.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Archer\Archer_Shoot.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Archer\Archer_Shoot.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-Mobile-2-Pass.shader'
  'Assets\Plugins\Demigiant\DOTween\Editor\DOTweenEditor.dll.mdb'
  'Assets\Images\Tiny Swords\Units\Blue Units\Monk\Heal.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Monk\Heal.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Monk\Heal.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Monk\Heal.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Monk\Heal.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\3. Button\256\2. Combined.png'
  'Assets\Images\Tiny Swords\Buildings\Yellow Buildings\Monastery.png'
  'Assets\Images\Tiny Swords\Buildings\Blue Buildings\Monastery.png'
  'Assets\Images\Tiny Swords\Buildings\Black Buildings\Monastery.png'
  'Assets\Images\Tiny Swords\Buildings\Purple Buildings\Monastery.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_Run.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_Run.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_Run.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_Run.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_Run.png'
  'Assets\Images\Tiny Swords\Buildings\Red Buildings\Monastery.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF Overlay.shader'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_Yellow.controller'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_Purple.controller'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_Black.controller'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_Blue.controller'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_Red.controller'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\Close Button.png'
  'Assets\Prefabs\PlayButton.prefab'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\FreeSamplesTiles.prefab'
  'Assets\Images\Tiny Swords\Buildings\Yellow Buildings\Archery.png'
  'Assets\Images\Tiny Swords\Buildings\Blue Buildings\Archery.png'
  'Assets\Images\Tiny Swords\Buildings\Black Buildings\Archery.png'
  'Assets\Images\Tiny Swords\Buildings\Purple Buildings\Archery.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\4. Sword\256\1. Sword.png'
  'Assets\Images\Tiny Swords\Buildings\Red Buildings\Archery.png'
  'Assets\Images\Tiny Swords\Buildings\Yellow Buildings\Barracks.png'
  'Assets\Images\Tiny Swords\Buildings\Blue Buildings\Barracks.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior_Idle.png'
  'Assets\Images\Tiny Swords\Buildings\Purple Buildings\Barracks.png'
  'Assets\Images\Tiny Swords\Buildings\Red Buildings\Barracks.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\5. Sword.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior_Idle.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior_Idle.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior_Idle.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior_Run.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior_Run.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior_Run.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior_Run.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior_Run.png'
  'Assets\Images\Tiny Swords\Units\Extra\Heal Effect\Heal_Effect.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior_Idle.png'
  'Assets\Save.json'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\12. Knives Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\7. Knives\512\2. Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\256\3. Combined.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior_Attack2.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior_Attack2.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior_Attack2.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior_Attack2.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior_Attack2.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\1. Card.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\256\1. Card.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_DownRight_Defence.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_DownRight_Defence.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_DownRight_Defence.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_DownRight_Defence.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_DownRight_Defence.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\6. Spear.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\7. Knife.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\6. Knife\256\1. Knife.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-Mobile Masking.shader'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\4. Button.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\Atlas.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior_Attack1.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior_Attack1.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior_Attack1.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior_Attack1.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior_Attack1.png'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-Mobile Overlay.shader'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_UpRight_Defence.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_UpRight_Defence.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_UpRight_Defence.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_UpRight_Defence.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior_Guard.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior_Guard.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_Right_Defence.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_Right_Defence.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior_Guard.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_Right_Defence.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_Right_Defence.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior_Guard.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_Right_Defence.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_Down_Defence.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_Down_Defence.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_Down_Defence.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\8. Knives.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_Down_Defence.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_Down_Defence.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\8. Coin\512\2. Shadow.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_Up_Defence.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_Up_Defence.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_Up_Defence.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_Up_Defence.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_Up_Defence.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\TextBTN_Big_Pressed.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_DownRight_Attack.png'
  'Assets\Terrain Tile Hex Samples\readme_tile_hex_samples.txt'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_DownRight_Attack.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_DownRight_Attack.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_DownRight_Attack.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_DownRight_Attack.png'
  'Assets\Images\Tiny Swords\Buildings\Yellow Buildings\Tower.png'
  'Assets\Images\Tiny Swords\Buildings\Blue Buildings\Tower.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Monk\Idle.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Monk\Idle.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Monk\Idle.png'
  'Assets\Images\Tiny Swords\Buildings\Black Buildings\Tower.png'
  'Assets\Images\Tiny Swords\Buildings\Purple Buildings\Tower.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Monk\Idle.png'
  'Assets\Images\Tiny Swords\Buildings\Red Buildings\Tower.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Inventory\Title_Box.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\3. Button\256\1. Button.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_Down_Attack.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_Down_Attack.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_Down_Attack.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_Down_Attack.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_Down_Attack.png'
  'Assets\TextMesh Pro\Shaders\SDFFunctions.hlsl'
  'Assets\Plugins\Demigiant\DOTween\Editor\DOTweenEditor.XML'
  'Assets\Images\Tiny Swords\Buildings\Red Buildings\House2.png'
  'Assets\Images\Tiny Swords\Buildings\Yellow Buildings\House2.png'
  'Assets\Images\Tiny Swords\Buildings\Purple Buildings\House2.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_UpRight_Attack.png'
  'Assets\Images\Tiny Swords\Buildings\Blue Buildings\House2.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_UpRight_Attack.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_UpRight_Attack.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_UpRight_Attack.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_UpRight_Attack.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Monk\Run.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Monk\Run.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Monk\Run.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Monk\Run.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Monk\Run.png'
  'Assets\TextMesh Pro\Shaders\TMPro_Mobile.cginc'
  'Assets\Images\Tiny Swords\Buildings\Purple Buildings\House1.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Archer\Archer_Run.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Archer\Archer_Run.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Archer\Archer_Run.png'
  'Assets\Images\Tiny Swords\Buildings\Yellow Buildings\House1.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Archer\Archer_Run.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Archer\Archer_Run.png'
  'Assets\Images\Tiny Swords\Buildings\Blue Buildings\House1.png'
  'Assets\Images\Tiny Swords\Buildings\Red Buildings\House1.png'
  'Assets\Images\Tiny Swords\Buildings\Black Buildings\House1.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior Yellow Animations\Warrior_Yellow.controller'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior Purple Animations\Warrior_Purple.controller'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior Black Animations\Warrior Black.controller'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior Blue Animations\Warrior_Blue.controller'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior Red Animations\Warrior.controller'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_Up_Attack.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_Up_Attack.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_Up_Attack.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_Up_Attack.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_Up_Attack.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Archer\Archer_Idle.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Archer\Archer_Idle.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Archer\Archer_Idle.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Archer\Archer_Idle.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\3. Button\128\2. Combined.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\5. Sword.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer_Right_Attack.png'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer_Right_Attack.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer_Right_Attack.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\4. Sword\128\1. Sword.png'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer_Right_Attack.png'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer_Right_Attack.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\Stats_Box.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\9. Sword Shadow.png'
  'Assets\TextMesh Pro\Fonts\LiberationSans - OFL.txt'
  'Assets\Images\Tiny Swords\Buildings\Yellow Buildings\House3.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\4. Sword\512\2. Shadow.png'
  'Assets\Images\Tiny Swords\Buildings\Red Buildings\House3.png'
  'Assets\Plugins\Demigiant\DOTween\Editor\Imgs\Footer_dark.png'
  'Assets\Images\Tiny Swords\Buildings\Black Buildings\House3.png'
  'Assets\Plugins\Demigiant\DOTween\Editor\Imgs\Footer.png'
  'Assets\Images\Tiny Swords\Buildings\Blue Buildings\House3.png'
  'Assets\Images\Tiny Swords\Buildings\Purple Buildings\House3.png'
  'Assets\Prefabs\Grid.prefab'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-Surface.shader'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\11. Knife Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\6. Knife\512\2. Shadow.png'
  'Assets\Images\StoneUI\Samples\button_moss_grey.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\7. Knives\256\2. Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\12. Knives Shadow.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Inventory\Inventory_Slot.png'
  'Assets\Images\Fantasy Wooden GUI  Free\normal_ui_set A\Division line.png'
  'Assets\TextMesh Pro\Sprites\EmojiOne.json'
  'Assets\TextMesh Pro\Shaders\TMP_Bitmap-Mobile.shader'
  'Assets\Images\Flat 2D Weapons\Art\PNG\5. Spear\256\1. Spear.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\5. Spear\512\1. Spear.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\6. Spear.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\128\3. Combined.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_Idle_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_Idle_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_Idle_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_Idle_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_Idle_Red.anim'
  'Assets\Images\Flat 2D Weapons\Art\PNG\6. Knife\128\1. Knife.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\7. Knife.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\128\1. Card.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\1. Card.png'
  'Assets\TextMesh Pro\Shaders\TMP_Bitmap.shader'
  'Assets\TextMesh Pro\Shaders\TMP_Bitmap-Custom-Atlas.shader'
  'Assets\Images\Tiny Swords\Units\Extra\Heal Effect\Heal_Animation.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Monk\Monk Purple Animations\Monk_Heal_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Monk\Monk Yellow Animations\Monk_Heal_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Monk\Monk Black Animations\Monk_Heal_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Monk\Monk Blue Animations\Monk_Heal_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Monk\Monk Red Animations\Monk_Heal_Red.anim'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\HexSpriteAtlas.spriteatlas'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\SquareTileSpriteAtlas.spriteatlas'
  'Assets\Images\Tiny Swords\Units\Purple Units\Archer\Archer Purple Animations\Archer_Purple.controller'
  'Assets\Images\Tiny Swords\Units\Black Units\Archer\Archer Black Animations\Archer_Black.controller'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Archer\Archer Yellow Animations\Archer_Yellow.controller'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Monk\Monk Yellow Animations\Monk_Yellow.controller'
  'Assets\Images\Tiny Swords\Units\Purple Units\Monk\Monk Purple Animations\Monk_Purple.controller'
  'Assets\Images\Tiny Swords\Units\Blue Units\Archer\Archer Blue Animations\Archer_Blue.controller'
  'Assets\Images\Tiny Swords\Units\Blue Units\Monk\Monk Blue Animations\Monk_Blue.controller'
  'Assets\Images\Tiny Swords\Units\Red Units\Archer\Archer Animations Red\Archer_Red.controller'
  'Assets\Images\Tiny Swords\Units\Red Units\Monk\Monk Red Animations\Monk_Red.controller'
  'Assets\Images\Tiny Swords\Units\Black Units\Monk\Monk Black Animations\Monk_Black.controller'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-Surface-Mobile.shader'
  'Assets\TextMesh Pro\Shaders\TMPro_Surface.cginc'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\512\2. Background of Card.png'
  'Assets\Images\Hero Knight - Pixel Art\Demo\SlideDust.prefab'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\2. Card Background.png'
  'Assets\Images\Hero Knight - Pixel Art\Demo\BlockFlash.prefab'
  'Assets\Images\Flat 2D Weapons\Art\PNG\8. Coin\256\2. Shadow.png'
  'Assets\Images\Hero Knight - Pixel Art\Sprites\HeroKnight_DeathNoBlood.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\3. Button\128\1. Button.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Inventory\Coin_Icon.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Coin_Icon.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Archer\Archer Purple Animations\Archer_Shoot_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Archer\Archer Yellow Animations\Archer_Shoot_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Archer\Archer Black Animations\Archer_Shoot_Black.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior Purple Animations\Warrior_Idle_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Archer\Archer Blue Animations\Archer_Shoot_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior Yellow Animations\Warrior_Idle_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Archer\Archer Animations Red\Archer_Shoot_Red.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior Black Animations\Warrior_Idle_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior Blue Animations\Warrior_Idle_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior Red Animations\Warrior_Idle_Red.anim'
  'Assets\TextMesh Pro\Shaders\TMP_SDF-Mobile SSD.shader'
  'Assets\Animations\PlayerPosition.controller'
  'Assets\Images\Hero Knight - Pixel Art\Animations\BlockFlash.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ Right_Defence_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ Right_Defence_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ DownRight_Defence_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ DownRight_Defence_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ Right_Defence_Black.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ DownRight_Defence_Black.anim'
  'Assets\Images\Hero Knight - Pixel Art\ColorSwap\swap_texture.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ UpRight_Defence_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ UpRight_Defence_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ Right_Defence_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ DownRight_Defence_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ UpRight_Defence_Black.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ DownRight_Defence_Red.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ Right_Defence_Red.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ UpRight_Defence_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ UpRight_Defence_Red.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ Down_Defence_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ Down_Defence_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ Down_Defence_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ Down_Defence_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ Down_Defence_Red.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior Purple Animations\Warrior_Guard_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior Yellow Animations\Warrior_Guard_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ Up_Defence_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior Black Animations\Warrior_Guard_Black.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ Up_Defence_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior Blue Animations\Warrior_Guard_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ Up_Defence_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ Up_Defence_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior Red Animations\Warrior_Guard_Red.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ Run_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ Run_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ Up_Defence_Red.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ Run_Black.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Archer\Archer Yellow Animations\Archer_Idle_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Archer\Archer Purple Animations\Archer_Idle_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior Yellow Animations\Warrior_Run_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior Purple Animations\Warrior_Run_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ Run_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ Run_Red.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior Black Animations\Warrior_Run_Black.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Monk\Monk Purple Animations\Monk_Idle_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior Blue Animations\Warrior_Run_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Archer\Archer Blue Animations\Archer_Idle_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Monk\Monk Yellow Animations\Monk_Idle_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Monk\Monk Black Animations\Monk_Idle_Black.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Archer\Archer Animations Red\Archer_Idle_Red.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior Red Animations\Warrior_Run_Red.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Monk\Monk Blue Animations\Monk_Idle_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Monk\Monk Red Animations\Monk_Idle_Red.anim'
  'Assets\TextMesh Pro\Shaders\TMPro_Properties.cginc'
  'Assets\Images\Tiny Swords\Units\Black Units\Archer\Archer Black Animations\Archer_Idle_Black.anim'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\Red_Ribbon.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\SlideDust.anim'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\Blue_Ribbon.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\Violet_Ribbon.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior Yellow Animations\Warrior_Attack1_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior Purple Animations\Warrior_Attack1_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior Black Animations\Warrior_Attack1_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior Blue Animations\Warrior_Attack1_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Warrior\Warrior Yellow Animations\Warrior_Attack2_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Warrior\Warrior Purple Animations\Warrior_Attack2_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior Red Animations\Warrior_Attack1_Red.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Warrior\Warrior Black Animations\Warrior_Attack2_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Warrior\Warrior Blue Animations\Warrior_Attack2_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Warrior\Warrior Red Animations\Warrior_Attack2_Red.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Monk\Monk Purple Animations\Monk_Run_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Archer\Archer Purple Animations\Archer_Run_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Archer\Archer Yellow Animations\Archer_Run_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Monk\Monk Yellow Animations\Monk_Run_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Archer\Archer Black Animations\Archer_Run_Black.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Monk\Monk Black Animations\Monk_Run_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Archer\Archer Blue Animations\Archer_Run_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Monk\Monk Blue Animations\Monk_Run_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Archer\Archer Animations Red\Archer_Run_Red.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Monk\Monk Red Animations\Monk_Run_Red.anim'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_DeathNoBlood.anim'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_Death.anim'
  'Assets\Images\Hero Knight - Pixel Art\ColorSwap\ColorSwap.mat'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_Roll.anim'
  'Assets\TextMesh Pro\Shaders\TMPro.cginc'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\3. Background.png'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ DownRight_Attack_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ DownRight_Attack_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ DownRight_Attack_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ DownRight_Attack_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ DownRight_Attack_Red.anim'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_Attack3.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ Right_Attack_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ Right_Attack_Yellow.anim'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\512\10. Spear Shadow.png'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ UpRight_Attack_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ UpRight_Attack_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ UpRight_Attack_Black.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ Right_Attack_Black.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ Up_Attack_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ Up_Attack_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ Right_Attack_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ UpRight_Attack_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ Up_Attack_Black.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ Right_Attack_Red.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ UpRight_Attack_Red.anim'
  'Assets\Images\Tiny Swords\Units\Purple Units\Lancer\Lancer Purple Animations\Lancer_ Down_Attack_Purple.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ Up_Attack_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Yellow Units\Lancer\Lancer Yellow Animations\Lancer_ Down_Attack_Yellow.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ Up_Attack_Red.anim'
  'Assets\Images\Tiny Swords\Units\Black Units\Lancer\Lancer Black Animations\Lancer_ Down_Attack_Black.anim'
  'Assets\Images\Tiny Swords\Units\Blue Units\Lancer\Lancer Blue Animations\Lancer_ Down_Attack_Blue.anim'
  'Assets\Images\Tiny Swords\Units\Red Units\Lancer\Lancer Red Animations\Lancer_ Down_Attack_Red.anim'
  'Assets\Plugins\Demigiant\DOTween\readme.txt'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\9. Sword Shadow.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_BlockIdle.anim'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_IdleBlock.anim'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_Idle.anim'
  'Assets\Images\Simple Fantasy GUI\PNG\Inventory\Money_Bar.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\BlockFlash_AnimController.controller'
  'Assets\Images\Flat 2D Weapons\Art\PNG\4. Sword\256\2. Shadow.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Close_Icon.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\SlideDust.controller'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\Nickname_Slot.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_WallSlide.anim'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\11. Knife Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\6. Knife\256\2. Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\7. Knives\128\2. Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\12. Knives Shadow.png'
  'Assets\Images\Tiny Swords\Units\Extra\Heal Effect\Heal.controller'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_Attack2.anim'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Accept_Icon.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Menu Panel\Button.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_BlockNoEffect.anim'
  'Assets\Images\Hero Knight - Pixel Art\ColorSwap\Sprites-ColorSwap.shader'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Bar\Health.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_LedgeGrab.anim'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_Block.anim'
  'Assets\Images\Flat 2D Weapons\Art\PNG\5. Spear\128\1. Spear.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\6. Spear.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_Fall.anim'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Bar\Mana.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\8. Coin\128\2. Shadow.png'
  'Assets\Images\Hero Knight - Pixel Art\Animations\HeroKnight_Jump.anim'
  'Assets\Images\Simple Fantasy GUI\PNG\Login Panel\LoginPassword_Box.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Armor_Icon.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\256\2. Background of Card.png'
  'Assets\Plugins\Demigiant\DOTween\Editor\Imgs\DOTweenIcon.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\2. Card Background.png'
  'Assets\Images\Hero Knight - Pixel Art\Sprites\HeroKnight_BlockNoEffect.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Sword_Icon.png'
  'Assets\Animations\PlayerWalk.anim'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Helmet_Icon.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Boots_Icon.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Loading Bar\Progress_Bar.png'
  'Assets\Images\Hero Knight - Pixel Art\Sprites\EnvironmentTiles.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\4. Sword\128\2. Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\9. Sword Shadow.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Plus_Icon.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\Plus_Icon.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\11. Knife Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\6. Knife\128\2. Shadow.png'
  'Assets\Images\Tiny Fantasy Icons\README.txt'
  'Assets\Images\Flat 2D Weapons\Art\PNG\5. Spear\512\2. Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\5. Spear\256\2. Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\10. Spear Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\256\3. Background.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Shield_Icon.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\2. Card\128\2. Background of Card.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\2. Card Background.png'
  'Assets\TileMap\hexDesertYellowCactiForest00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexDesertYellowCactiForest00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexForestPineSnowCovered00.asset'
  'Assets\TileMap\hexForestPineSnowCovered00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\desertYellowCactiForest00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\forestPineSnowCovered00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexForestBroadleaf01.asset'
  'Assets\TileMap\hexForestBroadleaf00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexForestBroadleaf00.asset'
  'Assets\TileMap\hexForestBroadleaf01.asset'
  'Assets\TileMap\hexVolcanoActive00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexVolcanoActive00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexPlainsCastle00.asset'
  'Assets\TileMap\hexPlainsCastle00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\forestBroadleaf00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexUnderOcean00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\plains_castle00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\volcanoActive00.asset'
  'Assets\TileMap\hexUnderOcean00.asset'
  'Assets\TileMap\hexUnderDirt00.asset'
  'Assets\TileMap\hexOceanCalm00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexUnderDirt00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexOceanCalm00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\below_water00.asset'
  'Assets\TileMap\hexMountain00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexMountain00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\below_dirt00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexPlains00.asset'
  'Assets\TileMap\hexJungle00.asset'
  'Assets\TileMap\hexPlains00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\oceanCalm00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexPlains02.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexJungle00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexPlains01.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\mountain00.asset'
  'Assets\TileMap\hexBase00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Hexes\hexBase00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\jungle00.asset'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\plains00.asset'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Comleted_Icon.png'
  'Assets\Terrain Tile Hex Samples\Example Scene\Example Tiles\base00.asset'
  'Assets\Images\Simple Fantasy GUI\PNG\Character Panel\Minus_Icon.png'
  'Assets\Images\Simple Fantasy GUI\PNG\Icons\Minus_Icon.png'
  'Assets\Images\Hero Knight - Pixel Art\Sprites\BlockFlash.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\5. Spear\128\2. Shadow.png'
  'Assets\Images\Flat 2D Weapons\Art\PNG\1. Collection\128\10. Spear Shadow.png'
  'Assets\Scripts\GameEvents\Events\CommandEvents\OnPlay_SendInfluenceCommandInformationToUndoButton.asset'
  'Assets\Scripts\GameEvents\Events\CommandEvents\OnPlay_SendExploreCommandInformationToUndoButton.asset'
  'Assets\Scripts\GameEvents\Events\CommandEvents\OnPlay_SendDefendCommandInformationToUndoButton.asset'
  'Assets\Scripts\GameEvents\Events\CommandEvents\OnPlay_SendAttackCommandInformationToUndoButton.asset'
  'Assets\Scripts\GameEvents\Events\CommandEvents\OnPlay_SendCommandInformationToUndoButton.asset'
  'Assets\Scripts\GameEvents\Events\ToggleEvents\OnToggle_SetInfluenceListenerCommand.asset'
  'Assets\Scripts\GameEvents\Events\Enemy Events\onNewEnemyCardCreation_SendCardData.asset'
  'Assets\Scripts\GameEvents\Events\ToggleEvents\OnToggle_SetExploreListenerCommand.asset'
  'Assets\Scripts\GameEvents\Events\ToggleEvents\OnToggle_SetDefendListenerCommand.asset'
  'Assets\Scripts\GameEvents\Events\ToggleEvents\OnToggle_SetAttackListenerCommand.asset'
  'Assets\Scripts\GameEvents\Events\Rewards\OnNewCardReward_OpenRewardScreen.asset'
  'Assets\Scripts\GameEvents\Events\TownEvents\onTownMenuClose_MinimizeTownCard.asset'
  'Assets\Scripts\GameEvents\Events\ToggleEvents\OnToggle_SetImprovButtonsOnOff.asset'
  'Assets\Images\Tiny Swords\Units\Extra\Arrow\Arrow.png'
  'Assets\Scripts\GameEvents\Events\Rewards\OnMenuOpen_GetCardReward.asset'
  'Assets\Images\Simple Fantasy GUI\PNG\Menu Panel\ButtonShadow.png'
  'Assets\Plugins\Demigiant\DOTween\Editor\Imgs\DOTweenMiniIcon.png'
  'Assets\Images\Hero Knight - Pixel Art\Sprites\SlideDust.png'
  'Assets\TextMesh Pro\Sprites\EmojiOne Attribution.txt'
  'Assets\Images\Hero Knight - Pixel Art\Sprites\Background.png'
  'Assets\UI Toolkit\UnityThemes\UnityDefaultRuntimeTheme.tss'
)
foreach ($t in $targets) {
  $full = Join-Path $root $t
  Recycle $full
  Recycle ($full + ".meta")
}
Write-Host ("Recycled {0} assets (+ their .meta files)." -f $targets.Count)
